# Generated by Django 5.1.4 on 2024-12-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
