# Generated by Django 5.1.4 on 2024-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_account_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_usernam_cab5ec_idx'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
