# Generated by Django 5.1.4 on 2024-12-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_account_accounts_usernam_cab5ec_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='main_app_ac_usernam_174efa_idx',
            old_name='accounts_usernam_cab5ec_idx',
        ),
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
    ]
