# Generated by Django 5.1.4 on 2024-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_accounts_usernam_cab5ec_idx_main_app_ac_usernam_174efa_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_usernam_cab5ec_idx',
            old_name='main_app_ac_usernam_174efa_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title', 'description'], name='tasks_title_674407_idx'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
