# Generated by Django 3.1.12 on 2025-04-22 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_resort_revues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(default='')),
                ('resort', models.TextField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Revues',
        ),
        migrations.AddField(
            model_name='resort',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
